    public function __call($method, $parameters)
    {
        try {
            return call_user_func_array([$this->connection(), $method], $parameters);
        } catch (Exception $exception) {
            throw $this->throwExceptionWithCredentials(new ConnectionException($exception->getMessage()));
        }
    }

    //////////////////////////////////////////////////////////////////////
    ////////////////////////////// HELPERS ///////////////////////////////
    //////////////////////////////////////////////////////////////////////

    /**
     * Throw an exception and display the credentials that failed with it*.
     *
     * @param CredentialsExceptionInterface $exception
     *
     * @return CredentialsExceptionInterface
     */
||||||||||||||||HAS_DOC_COMMENTNO_RETURN_TYPE
(NO_PARAM_TYPENO_PARAM_DEFAULTNO_PARAM_TYPENO_PARAM_DEFAULT)
(
    (AST_TRY
        (
            (AST_RETURN
                (AST_CALL
                    (
                        (AST_ARRAY
                            (AST_ARRAY_ELEM
                                (AST_METHOD_CALL
                                    (AST_VAR))
                                (NULL))
                            (AST_ARRAY_ELEM
                                (AST_VAR)
                                (NULL)))
                        (AST_VAR)))))
        (AST_CATCH_LIST
            (AST_CATCH
                (AST_NAME_LIST)
                (AST_VAR)
                (
                    (AST_THROW
                        (AST_METHOD_CALL
                            (AST_VAR)
                            (
                                (AST_NEW
                                    (
                                        (AST_METHOD_CALL
                                            (AST_VAR))))))))))
        (NULL)))||||||||